More while loops

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -10,10 +10,10 @@ errror () {
 # Check if a command exists
 check_cmd () {
   if ! type "$1" > /dev/null; then
-      errror
-      echo "$1 was not found in your path!"
-      echo "To proceed please install $1 to your path and try again!"
-      exit 1
+    errror
+    echo "$1 was not found in your path!"
+    echo "To proceed please install $1 to your path and try again!"
+    exit 1
   fi
 }
 
