chkdir

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -1,5 +1,17 @@
 #!/bin/bash
 
+chkdir () {
+  if [ ! -w $1 ] ; then
+    sudo mkdir -p $1
+    sudo chown $USER. $1
+  fi
+  if [ ! -w $1 ] ; then
+    errror
+    echo "Cannot write to $1, please check your permissions"
+    exit 2
+  fi
+}
+
 # these vars are used by the following functions
 LINE_TO_ADD=''
 TARGET_FILE_FOR_ADD=~/.profile
